"""
Receives per-frame results from pipeline.py.

Results are stored in PostgreSQL and broadcast to connected
dashboard clients over WebSockets.
"""

from datetime import datetime, timezone

from fastapi import APIRouter, Depends
from pydantic import BaseModel, Field
from sqlalchemy.orm import Session

from backend.database import get_db
from backend import models
from backend.routers.stream import broadcaster


router = APIRouter(
    prefix="/api/ingest",
    tags=["ingest"],
)


class DetectionIn(BaseModel):
    track_id: int
    class_name: str
    confidence: float

    x1: float
    y1: float
    x2: float
    y2: float

    center_x: float
    center_y: float

    behavior: str | None = None
    behavior_confidence: float | None = None

    in_restricted_zone: bool = False

    direction: str | None = None
    velocity: float | None = None
    acceleration: float | None = None


class ZoneEventIn(BaseModel):
    track_id: int
    event_type: str


class AnomalyEventIn(BaseModel):
    track_id: int
    reasons: list[str]


class FrameIngest(BaseModel):
    # Generated by monitoring.py and passed through pipeline.py.
    session_id: str | None = None

    detections: list[DetectionIn] = Field(default_factory=list)
    zone_events: list[ZoneEventIn] = Field(default_factory=list)
    anomaly_events: list[AnomalyEventIn] = Field(default_factory=list)


@router.post("/frame")
async def ingest_frame(
    payload: FrameIngest,
    db: Session = Depends(get_db),
):
    session_id = payload.session_id

    try:
        # Convert incoming data to dictionaries and attach the session.
        detection_records = [
            {
                **d.model_dump(),
                "session_id": session_id,
            }
            for d in payload.detections
        ]

        zone_event_records = [
            {
                **event.model_dump(),
                "session_id": session_id,
            }
            for event in payload.zone_events
        ]

        anomaly_event_records = [
            {
                **event.model_dump(),
                "session_id": session_id,
            }
            for event in payload.anomaly_events
        ]

        # Persist all records from this frame in one transaction.
        if detection_records:
            db.add_all(
                [
                    models.Detection(**record)
                    for record in detection_records
                ]
            )

        if zone_event_records:
            db.add_all(
                [
                    models.ZoneEvent(**record)
                    for record in zone_event_records
                ]
            )

        if anomaly_event_records:
            db.add_all(
                [
                    models.AnomalyEvent(**record)
                    for record in anomaly_event_records
                ]
            )

        db.commit()

    except Exception:
        db.rollback()
        raise

    timestamp = datetime.now(timezone.utc).isoformat()

    # Broadcast the same session-aware records to live dashboard clients.
    await broadcaster.broadcast(
        {
            "type": "frame",
            "session_id": session_id,
            "timestamp": timestamp,
            "detections": detection_records,
            "zone_events": zone_event_records,
            "anomaly_events": anomaly_event_records,
        }
    )

    return {
        "status": "ok",
        "session_id": session_id,
        "ingested": len(detection_records),
        "zone_events": len(zone_event_records),
        "anomaly_events": len(anomaly_event_records),
    }